import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  StatusBar,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTheme } from '../../theme/ThemeProvider';
import ScreenHeader from '../../components/ScreenHeader';

export default function TermsAndConditionsScreen({ navigation }: { navigation: any }) {
  const insets = useSafeAreaInsets();
  const { theme, isDark } = useTheme();
  const c = theme.colors;

  return (
    <View style={[styles.container, { backgroundColor: c.background, paddingTop: insets.top }]}>
      <StatusBar barStyle={isDark ? 'light-content' : 'dark-content'} backgroundColor="transparent" translucent />
      
      <ScreenHeader title="Terms and Conditions" onBack={() => navigation.goBack()} />

      <ScrollView contentContainerStyle={{ paddingHorizontal: 24, paddingBottom: insets.bottom + 40 }}>
        <Text style={[styles.date, { color: c.text }]}>Last Updated: [Insert Date]</Text>

        <Text style={[styles.paragraph, { color: c.text }]}>
          Welcome to MyHealthNotion. By accessing or using our app, you agree to the following terms.
        </Text>

        <Text style={[styles.heading, { color: c.text }]}>1. Acceptance of Terms</Text>
        <Text style={[styles.paragraph, { color: c.text }]}>
          By using MyHealthNotion, you agree to comply with and be bound by these Terms. If you do not agree, please do not use the app.
        </Text>

        <Text style={[styles.heading, { color: c.text }]}>2. Description of Service</Text>
        <Text style={[styles.paragraph, { color: c.text }]}>
          MyHealthNotion provides users with tools to:
        </Text>
        <View style={styles.list}>
          <Text style={[styles.listItem, { color: c.text }]}>• Track health data</Text>
          <Text style={[styles.listItem, { color: c.text }]}>• Store medical records</Text>
          <Text style={[styles.listItem, { color: c.text }]}>• Receive AI-powered insights and recommendations</Text>
        </View>
        <Text style={[styles.paragraph, { color: c.text }]}>
          ⚠️ Important: MyHealthNotion does NOT provide medical advice. Always consult a qualified healthcare professional.
        </Text>

        <Text style={[styles.heading, { color: c.text }]}>3. User Responsibilities</Text>
        <Text style={[styles.paragraph, { color: c.text }]}>
          You agree to:
        </Text>
        <View style={styles.list}>
          <Text style={[styles.listItem, { color: c.text }]}>• Provide accurate and complete information</Text>
          <Text style={[styles.listItem, { color: c.text }]}>• Use the app only for lawful purposes</Text>
          <Text style={[styles.listItem, { color: c.text }]}>• Not misuse, hack, or disrupt the platform</Text>
        </View>

        <Text style={[styles.heading, { color: c.text }]}>4. Medical Disclaimer</Text>
        <Text style={[styles.paragraph, { color: c.text }]}>
          All insights, suggestions, or outputs generated by the app are:
        </Text>
        <View style={styles.list}>
          <Text style={[styles.listItem, { color: c.text }]}>• Informational only</Text>
          <Text style={[styles.listItem, { color: c.text }]}>• Not a substitute for professional medical advice, diagnosis, or treatment</Text>
        </View>

        <Text style={[styles.heading, { color: c.text }]}>5. Data Usage</Text>
        <Text style={[styles.paragraph, { color: c.text }]}>
          Your data is handled in accordance with our Privacy Policy.
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  date: {
    fontFamily: 'Manrope-SemiBold',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 24,
  },
  heading: {
    fontFamily: 'Manrope-Medium',
    fontSize: 16,
    lineHeight: 20,
    marginTop: 16,
    marginBottom: 8,
  },
  paragraph: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 8,
  },
  list: {
    marginLeft: 8,
    marginBottom: 8,
  },
  listItem: {
    fontFamily: 'Manrope-Regular',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 4,
  },
});
